"""init

Revision ID: fc188e955d7d
Revises: 1c85c8b57b66
Create Date: 2026-04-13 13:14:46.387004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc188e955d7d'
down_revision: Union[str, None] = '1c85c8b57b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_slug_key'), 'courses', type_='unique')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.drop_constraint(op.f('teachers_email_key'), 'teachers', type_='unique')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=False)
    op.create_unique_constraint(op.f('teachers_email_key'), 'teachers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=False)
    op.create_unique_constraint(op.f('courses_slug_key'), 'courses', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###